"""Use pgvector for embedding

Revision ID: f4f89199e52d
Revises: 
Create Date: 2025-11-29 06:37:03.986628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f4f89199e52d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # Remove the problematic alter_column for embedding
    # op.alter_column('chunks', 'embedding',
    #            existing_type=sa.TEXT(),
    #            type_=pgvector.sqlalchemy.Vector(dim=384),
    #            existing_nullable=True)
    # Use raw SQL with USING clause for vector conversion
    op.execute(
        "ALTER TABLE chunks ALTER COLUMN embedding TYPE vector(384) USING embedding::vector(384);"
    )
    op.drop_index('ix_chunks_document_id', table_name='chunks')
    op.drop_column('chunks', 'embedding_vector')
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'modality',
               existing_type=postgresql.ENUM('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'PDF', name='modalitytype'),
               nullable=True)
    op.alter_column('documents', 'doc_metadata',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_documents_title', table_name='documents')
    op.drop_column('documents', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_documents_title', 'documents', ['title'], unique=False)
    op.alter_column('documents', 'doc_metadata',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'modality',
               existing_type=postgresql.ENUM('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'PDF', name='modalitytype'),
               nullable=False)
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('chunks', sa.Column('embedding_vector', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=384),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
